# Generated by Django 3.2.9 on 2021-12-03 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=40)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=400)),
                ('publish_date', models.DateField(default=datetime.date)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='img/')),
            ],
        ),
    ]
