# Generated by Django 3.1 on 2021-11-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
