# Generated by Django 3.2.9 on 2021-12-03 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_details_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
