# Generated by Django 3.2.9 on 2021-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_details_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=30)),
                ('phone', models.IntegerField(default='', max_length=11)),
                ('msg', models.CharField(default='', max_length=900)),
            ],
        ),
    ]
