# Generated by Django 3.2.9 on 2021-12-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
