# Generated by Django 3.2.9 on 2021-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_whish_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='created_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
